version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:alpine